import { brandConfig } from "@/brand/config";
import { getBlogPost } from "@/lib/data";

import type { Metadata } from "next";
import { getTranslations } from "next-intl/server";
import Link from "next/link";
import { notFound } from "next/navigation";

type PageProps = {
  params: Promise<{ locale: string; slug: string }>;
};

export const generateMetadata = async ({
  params,
}: PageProps): Promise<Metadata> => {
  const { locale, slug } = await params;

  const post = await getBlogPost(locale, slug);
  const t = await getTranslations({
    locale,
    namespace: "Meta.BlogPost",
  });

  const base = brandConfig.appUrl;
  const path = `/${locale}/blog/${slug}`;

  const title = post
    ? `${t("TitlePrefix")}${post.title}`
    : t("TitlePrefix") + slug;

  const description = post
    ? `${post.excerpt}${t("DescriptionSuffix")}`
    : t("DescriptionSuffix");

  return {
    title,
    description,
    alternates: {
      canonical: `${base}${path}`,
      languages: {
        en: `${base}/en/blog/${slug}`,
        ar: `${base}/ar/blog/${slug}`,
      },
    },
  };
};

const BlogPostPage = async ({ params }: PageProps) => {
  const { locale, slug } = await params;

  const post = await getBlogPost(locale, slug);
  if (!post) {
    notFound();
  }

  const t = await getTranslations({ locale, namespace: "BlogPost" });

  const publishedDate = new Date(post.publishedAt);
  const formattedDate =
    locale === "ar"
      ? publishedDate.toLocaleDateString("ar-EG", {
          year: "numeric",
          month: "long",
          day: "numeric",
        })
      : publishedDate.toLocaleDateString("en-US", {
          year: "numeric",
          month: "long",
          day: "numeric",
        });

  return (
    <main className="py-5">
      <nav className="mb-4">
        <Link href={`/${locale}/blog`} className="text-decoration-none">
          &larr; {t("backToBlog")}
        </Link>
      </nav>

      <article>
        <header className="mb-4">
          <h1 className="mb-2">{post.title}</h1>
          <p className="text-muted small mb-1">
            {t("publishedOn")}: {formattedDate}
          </p>
          {post.tags?.length ? (
            <p className="small mb-0">
              <span className="fw-semibold">{t("tagsLabel")}:</span>{" "}
              {post.tags.join(", ")}
            </p>
          ) : null}
        </header>

        {/* contentHtml is assumed to be safe HTML generated by your backend */}
        <section
          className="blog-post-content"
          dangerouslySetInnerHTML={{ __html: post.contentHtml }}
        />
      </article>
    </main>
  );
};

export default BlogPostPage;
